services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wacdo_app
    # ports:
    #   - "${APP_PORT}:80"
    volumes:
      - .:/var/www/html
      - uploads_data:/var/www/html/storage/uploads
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: wacdo_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database:/scripts:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  db_data:
  uploads_data:
